name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_MODE: ${{ secrets.DJANGO_MODE }}
      HOST_IP: ${{ secrets.HOST_IP }}
      HOST_NAME: ${{ secrets.HOST_NAME }}


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
