name: Test Applciation Running


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Build
      run: docker-compose build

    - name: Docker Compose Up
      run: docker-compose up -d

    - name: Wait for Application to be ready
      run: sleep 10 # Wait for 10 seconds for application to be ready
    
    - name: Print application logs
      run: docker-compose logs

    - name: Test Application
      run: |
        echo "Starting application test..."
        wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 -O- --spider http://localhost:8001/predict
        if [ $? -ne 0 ]; then
          echo "ERROR: Failed to connect with the Application." >&2
          exit 1
        else 
          echo "SUCCESS: Application is up and running."
        fi
    