name: Test Applciation Running


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Build
      run: docker-compose build

    - name: Docker Compose Up
      run: docker-compose up -d

    - name: Wait for Application to be ready
      run: sleep 10 # Wait for 10 seconds for application to be ready
    
    - name: Print application logs
      run: docker-compose logs
    
    - name: Test Application
      run: |
        APP_CONTAINER_ID=$(docker ps -aqf "name=your_container_name")
        docker exec $APP_CONTAINER_ID your_test_command_here
        if [ $? -ne 0 ]; then
          echo "Failed to connect with the Application" && exit 1
        else 
          echo "Application is up and running"
        fi