name: Test Application Running

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      app:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
        - 8001:8000
        options: --health-cmd "wget --quiet --spider http://localhost:8000/predict || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Build
      run: docker-compose build

    - name: Docker Compose Up
      run: docker-compose up -d

    - name: Wait for Application to be ready
      run: sleep 60 # Wait for 60 seconds for application to be ready
    
    - name: Print application logs
      run: docker-compose logs

    - name: Check application is running
      run: |
        wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 -O- --spider http://localhost:8001/predict
        if [ $? -ne 0 ]; then
          echo "Failed to connect with the Application" && exit 1
        else 
          echo "Application is up and running"
        fi
